ThePalaceProject/ios-audiobooktoolkit

Cartfile.resolved
NYPLAudiobookToolkit/UI/AudiobookPlayerViewController.swift
NYPLAudiobookToolkit/UI/AudiobookTrackTableViewCell.swift
NYPLAudiobookToolkit/UI/ChapterInfoStack.swift
NYPLAudiobookToolkit/UI/DownloadProgressView.swift
NYPLAudiobookToolkit/UI/ScrubberView.swift
NYPLAudiobookToolkit/UI/TextWithImageView.swift

Update audiobook controller to support dark mode
https://user-images.githubusercontent.com/6921353/127223650-e20a4b93-e627-40d5-b6f6-399193ce875c.mov

Dark Mode Support

---

NYPLAudiobookToolkit/Network/OpenAccessDownloadTask.swift

Resolves: 
https://www.notion.so/lyrasis/Error-Download-Failed-on-DPLA-Demarque-content-in-Palace-c6e65438866144a99a00473d543ef341

Exclude Authorization headers for cantookAudio books

---

NYPLAudiobookToolkit/Core/LCPSpineElement.swift
NYPLAudiobookToolkit/Core/OpenAccessSpineElement.swift
NYPLAudiobookToolkit/Core/OverdriveSpineElement.swift
NYPLAudiobookToolkit/UI/AudiobookPlayerViewController.swift

Update Audiobook to show "Track" instead of "Chapter"

Update Audiobook to show "Track" instead of "Chapter"

---

NYPLAudiobookToolkit.xcodeproj/project.pbxproj
NYPLAudiobookToolkit/Core/LCPAudiobook.swift
NYPLAudiobookToolkit/Core/LCPSpineElement.swift
NYPLAudiobookToolkit/Extensions/Array+Extensions.swift
NYPLAudiobookToolkit/Extensions/String+Extensions.swift
NYPLAudiobookToolkitTests/AudiobookTOCTests.swift
NYPLAudiobookToolkitTests/TestResources/non_toc_manifest.json
NYPLAudiobookToolkitTests/TestResources/toc_manifest.json

https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=490d677e84b34ca9935a225ef0ac120e&p=b60097865f374c4ba6ec3bed69a0c441
Implements logic to build spine from TOC and unit tests

Implements logic to build spine from TOC and unit tests

---

NYPLAudiobookToolkit/Player/OpenAccessPlayer.swift
NYPLAudiobookToolkit/Player/Player.swift

https://www.notion.so/lyrasis/Audiobook-playback-speed-not-saved-after-closing-book-ed53e2708e1044f8b5a6b225e03e4d36

Persist playback speed

---

NYPLAudiobookToolkit/Core/OpenAccessSpineElement.swift

When building the spine element, alternate links must be checked to determine if an element is supported.

Check alternate links before deciding if element is supported or not

---

NYPLAudiobookToolkit/UI/AudiobookCoverImageView.swift

https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=490d677e84b34ca9935a225ef0ac120e&p=0857456af185463abf6c46f390b3a159

Fix AudiobookCoverImageView's content mode to prevent cropping

---

NYPLAudiobookToolkit/Network/OpenAccessDownloadTask.swift
NYPLAudiobookToolkit/Player/Player.swift
NYPLAudiobookToolkitTests/ChapterLocationTests.swift

https://www.notion.so/lyrasis/iOS-Sync-audiobook-listening-position-to-server-98aaa6fa8dad4a60b617fafa5f830750?d=3a3ab32474014a79b8ecdd33bd7fd615

Support location syncing of legacy bookmarks

---

NYPLAudiobookToolkit/Player/OpenAccessPlayer.swift
NYPLAudiobookToolkit/Player/Player.swift

https://www.notion.so/lyrasis/Audiobook-being-interrupted-by-other-app-audio-b22e10bceebc42df9a80fc8f20fb8b96

Restart audiobook play following system interruption

---

NYPLAudiobookToolkit/Core/Cursor.swift
NYPLAudiobookToolkit/Player/OpenAccessPlayer.swift
NYPLAudiobookToolkit/Player/Player.swift
NYPLAudiobookToolkitTests/ChapterLocationTests.swift
NYPLAudiobookToolkitTests/PlayerManipulationTest.swift

https://www.notion.so/lyrasis/Skipping-backwards-past-a-chapter-boundary-takes-you-to-the-wrong-chapter-4f56159b0a744141adabfa1b72bee4fd

Resolve Audiobook step issues

---

NYPLAudiobookToolkit/Core/AudiobookManager.swift
NYPLAudiobookToolkit/Player/Player.swift
NYPLAudiobookToolkit/UI/AudiobookPlayerViewController.swift

Implements `PlaybackPositionDelegate` to communicate location saves to application

Save location at important audiobook events

---

NYPLAudiobookToolkit/Core/AudiobookManager.swift

Set the correct source when publishing annotations.

Set the correct source when publishing annotations.

---

NYPLAudiobookToolkit/Core/Audiobook.swift
NYPLAudiobookToolkit/Core/AudiobookManager.swift
NYPLAudiobookToolkit/Core/LCPAudiobook.swift
NYPLAudiobookToolkit/Core/OpenAccessAudiobook.swift
NYPLAudiobookToolkit/Core/OverdriveAudiobook.swift
NYPLAudiobookToolkit/UI/AudiobookPlayerViewController.swift
NYPLAudiobookToolkit/UI/AudiobookTableOfContentsTableViewController.swift

Resolves:
- https://www.notion.so/lyrasis/App-crashes-when-toggling-between-Chapters-and-Bookmarks-38f42093383243c9b9c4e93c3688280e
- https://www.notion.so/lyrasis/App-crashes-when-toggling-between-Chapters-and-Bookmarks-38f42093383243c9b9c4e93c3688280e
- https://www.notion.so/lyrasis/Text-from-Bookmarks-screen-appears-on-Chapters-screen-159881b4676f4157a40f5d833fd8433f?pvs=4

Resolves audiobook bookmarks issues

---

NYPLAudiobookToolkit.xcodeproj/project.pbxproj
NYPLAudiobookToolkit/Core/AudiobookManager.swift
NYPLAudiobookToolkit/Tracker/AudiobookPlaybackTrackerDelegate.swift

Adds time tracker delegate methods to AudiobookManager ([Ticket](https://ebce-lyrasis.atlassian.net/browse/PP-150))

PP-150 implement mobile time tracking functionality on iOS

---

NYPLAudiobookToolkit/Network/OpenAccessDownloadTask.swift
NYPLAudiobookToolkit/Network/OverdriveDownloadTask.swift

This fixes the issue with multiple file downloads 
A fix for [PP-87](https://ebce-lyrasis.atlassian.net/browse/PP-87), the issue described in [PP-316](https://ebce-lyrasis.atlassian.net/browse/PP-316).
[PP-87]: https://ebce-lyrasis.atlassian.net/browse/PP-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PP-316]: https://ebce-lyrasis.atlassian.net/browse/PP-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-87 Fix the issue with multiple file downloads

---

NYPLAudiobookToolkit/Player/ChapterLocation.swift
NYPLAudiobookToolkit/Player/SleepTimer.swift

Show user friendly sleep time duration 
Resolves:
https://ebce-lyrasis.atlassian.net/browse/PP-355

Show user friendly sleep time duration

---

PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift

Adds "Play" and "Pause" labels to the play/pause button in the player

Add play/pause button labels

---

PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkit/UI/AudiobookPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift

Fixes 0% progress text label [PP-551](https://ebce-lyrasis.atlassian.net/browse/PP-551)
[PP-551]: https://ebce-lyrasis.atlassian.net/browse/PP-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-551 Fix progress bar always showing 0%

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkit/UI/AudiobookPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift

Changes skip time interval to 30 s [PP-534](https://ebce-lyrasis.atlassian.net/browse/PP-534)
[PP-534]: https://ebce-lyrasis.atlassian.net/browse/PP-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-534 Change advance/rewind buttons to 30 seconds

---

PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift

Moves `fetchBookmarks` from view init() to model init() - view updates every second

PP-673 Fix bookmark fetching every second

---

PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift

Initialize currentLocation with default value on start

PP-552 Fix zero remaining time in audiobooks on start

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Network/OpenAccessDownloadTask.swift
PalaceAudiobookToolkit/Network/OverdriveDownloadTask.swift
PalaceAudiobookToolkit/Utils/URLRequest+Extensions.swift

Update UserAgent to be more detailed
https://ebce-lyrasis.atlassian.net/browse/PP-813

[PP-813] Update UserAgent to be more detailed

---

PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift

https://ebce-lyrasis.atlassian.net/browse/PP-790
Adds pull to refresh to navigation view

[PP-790] Update AudiobookNavigationView.swift

---

PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift

https://ebce-lyrasis.atlassian.net/browse/PP-809

[PP-809] Updates audiobook player seek logic

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Core/LCPAudiobook.swift
PalaceAudiobookToolkitTests/AudiobookTOCTests.swift
PalaceAudiobookToolkitTests/TestResources/anathem_manifest.json
PalaceAudiobookToolkitTests/TestResources/the_system_of_the_world_manifest.json

https://ebce-lyrasis.atlassian.net/browse/PP-934

[PP-934] Correctly parse TOCs with chapters spanning multiple files

---

PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift

https://ebce-lyrasis.atlassian.net/browse/PP-969

[PP-969] Restart audiobook at last saved position

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift

https://ebce-lyrasis.atlassian.net/browse/PP-934

[PP-969] Pause book after restart

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift

https://ebce-lyrasis.atlassian.net/browse/PP-969

[PP-861] Return to last saved position

---

PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift
PalaceAudiobookToolkit/Utils/Strings.swift

https://ebce-lyrasis.atlassian.net/browse/PP-861

[PP-861] Improve accessibility

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Core/Cursor.swift
PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift
PalaceAudiobookToolkit/Player/Player.swift
PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkitTests/AudiobookTOCTests.swift

[PP-995](https://ebce-lyrasis.atlassian.net/browse/PP-995)
[PP-994](https://ebce-lyrasis.atlassian.net/browse/PP-994)
[PP-995]: https://ebce-lyrasis.atlassian.net/browse/PP-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PP-994]: https://ebce-lyrasis.atlassian.net/browse/PP-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PP-995] Resolve OpenAcccess playback errors

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkitTests/PlayerMock.swift
PalaceAudiobookToolkitTests/TestResources/theBigFail_manifest.json

Fixes for a couple issues I had running audio book tests when trying to get an environment setup. 
Thread in slack here: 
https://lyrasis.slack.com/archives/C03GKDAKU0H/p1709660776404739
Thanks @mauricecarrier7 for helping me get this sorted out.

Fixes for a couple issues I had running tests (PP-1036)

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Player/ChapterLocation.swift
PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift
PalaceAudiobookToolkitTests/ChapterLocationTests.swift
PalaceAudiobookToolkitTests/PlayerMock.swift

Resolves outstanding ChapterLocation issues preventing last listening position from syncing

[PP-1013] Resolve outstanding ChapterLocation issues

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Network/AudiobookNetworkService.swift
PalaceAudiobookToolkit/Network/DownloadTask.swift
PalaceAudiobookToolkit/Network/FindawayDownloadTask.swift
PalaceAudiobookToolkit/Network/LCPDownloadTask.swift
PalaceAudiobookToolkit/Network/OpenAccessDownloadTask.swift
PalaceAudiobookToolkit/Network/OverdriveDownloadTask.swift
PalaceAudiobookToolkit/Player/Helpers/Models/AudiobookTableOfContents.swift
PalaceAudiobookToolkit/Player/Helpers/Tracks/Track.swift
PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkit/UI/RetryToolbar.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1349

[PP-1349] Implement updated audiobook TOC design

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Network/AudiobookNetworkService.swift
PalaceAudiobookToolkit/Player/Helpers/Models/AudiobookTableOfContents.swift
PalaceAudiobookToolkit/Player/Helpers/Models/Chapter.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift

- Re-order track downloads
- Ensure correct title is shown on lock screen

[PP-1371][PP-1382] Minor bug fixes 

---

PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1406

[PP-1406] TOC navigation not working as expected

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Player/Helpers/Models/AudiobookTableOfContents.swift
PalaceAudiobookToolkit/Player/Helpers/Models/Manifest.swift
PalaceAudiobookToolkit/Player/Helpers/Tracks/Tracks.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkitTests/ManifestJSON.swift
PalaceAudiobookToolkitTests/TestResources/where_the_line_is_drawn_manifest.json

https://ebce-lyrasis.atlassian.net/browse/PP-1408
https://ebce-lyrasis.atlassian.net/browse/PP-1440

PP-1408 Update how chapter titles are displayed

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Player/Helpers/Models/AudiobookTableOfContents.swift
PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1422
https://ebce-lyrasis.atlassian.net/browse/PP-1428
https://ebce-lyrasis.atlassian.net/browse/PP-1364

[PP-1422] Properly display local annotations

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Player/Helpers/Tracks/Tracks.swift
PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1438

[PP-1438] Restore cross platform syncing

---

PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift

Only rebuild player queue on download completion prior to playback beginning to prevent UI lock and restart

[PP-1504] Non LCP playback issues

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1678

PP-1678 Add back playback tracker functionality

---

PalaceAudiobookToolkit/Network/OverdriveDownloadTask.swift
PalaceAudiobookToolkit/Player/Helpers/Tracks/OverdriveTrack.swift
PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1707?atlOrigin=eyJpIjoiMDlhYjMxMDlkZWU0NDI4MmFmYTk1ZmY2ZjdiNjliMjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
https://ebce-lyrasis.atlassian.net/browse/PP-1671

[PP-1707] Set unique cache key for overdrive titles

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkit/UI/AudiobookPlayer.swift
PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift

Modifies code that increased CPU usage to prevent background crashes when playing audiobooks.

[PP-1645] Resolves CPU utilization crash

---

PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1722

PP-1722 Dont pause audiobook on background

---

PalaceAudiobookToolkit/Core/MediaControlPublisher.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1672

[PP-1672] Enable bluetooth player control

---

PalaceAudiobookToolkit/Player/Helpers/Models/AudiobookTableOfContents.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1801

[PP-1801] Calculate chapter end correctly for overdrive titles during move

---

PalaceAudiobookToolkit/Core/AudiobookManager.swift

https://ebce-lyrasis.atlassian.net/browse/PP-1790

[PP-1790] Update AudiobookManager.swift

---

PalaceAudiobookToolkit/Player/Helpers/Tracks/FindawayTrack.swift

https://ebce-lyrasis.atlassian.net/jira/software/c/projects/PP/boards/4?assignee=557058%3A5935cd45-cdea-4ef2-8d5c-a11268527fba&selectedIssue=PP-1764

[PP-1764] Restore findaway audiobook cross platform sync functionality 

---

PalaceAudiobookToolkit.xcodeproj/project.pbxproj
PalaceAudiobookToolkit/Core/AudiobookManager.swift
PalaceAudiobookToolkit/Core/Log.swift
PalaceAudiobookToolkit/Player/HTTPRangeRetriever.swift
PalaceAudiobookToolkit/Player/Helpers/Models/AudiobookTableOfContents.swift
PalaceAudiobookToolkit/Player/LCPPlayer.swift
PalaceAudiobookToolkit/Player/LCPStreamingPlayer.swift
PalaceAudiobookToolkit/Player/OpenAccessPlayer.swift
PalaceAudiobookToolkit/Player/UnifiedPositionSystem.swift
PalaceAudiobookToolkit/UI/AudiobookNavigationView.swift
PalaceAudiobookToolkit/UI/AudiobookPlaybackModel.swift
PalaceAudiobookToolkit/UI/AudiobookPlayerView.swift
PalaceAudiobookToolkit/UI/ChapterCell.swift
PalaceAudiobookToolkitTests/UnifiedPositionSystemTests.swift

Comprehensive improvements to audiobook player functionality, addressing navigation issues, seeking behavior, and UI responsiveness for a smoother user experience.
- 30-second skips now work to the end of chapters (removed restrictive safety zones)  
- Audiobooks always start at the first chapter (fixed random starting positions on initial download)  
- Eliminated audio restarts during initialization → smooth loading without interruptions  
- Play/pause button updates immediately when pressed  
- Smooth seeking without UI blinking (especially for non-LCP audiobooks)  
- Real-time state synchronization between player and UI  
- Consistent starting behavior across all audiobook types  
- Better bookmark validation to prevent corrupted position data  
- Coordinated playback control → no …

Audiobookplayer improvements
